#!/bin/bash -x

set -x

APPLY_TIMESTAMP=${APPLY_TIMESTAMP:-"null"}

RECIPE_DIR="$(dirname $0)"
while [ ! -d "${RECIPE_DIR}/conf" ];
do
    RECIPE_DIR="$(dirname ${RECIPE_DIR})"
done
test -z "${OEROOT}" && OEROOT=$(readlink -f ${RECIPE_DIR}/../poky)
. ${OEROOT}/scripts/oe-init-bashrc

DEPLOY_DIR_IMAGE_BASE="${BUILDDIR}/tmp/deploy/images"
DEPLOY_DIR_SDK_BASE="${BUILDDIR}/tmp/deploy/sdk"
MACHINES="$(ls ${DEPLOY_DIR_IMAGE_BASE})"

MANISPC=""
for MACHINE in ${MACHINES}
do
    DEPLOY_DIR_IMAGE="${DEPLOY_DIR_IMAGE_BASE}/${MACHINE}"

    BUNDLE_MANIFEST=$(ls ${DEPLOY_DIR_IMAGE}/.updatable-*-bundle-*-${MACHINE}-manifest)
    BUNDLE_VERSION=${BUNDLE_VERSION:-$(. ${BUNDLE_MANIFEST}; echo ${VERSION})}
    WANTED_ROOT_DEV=${WANTED_ROOT_DEV:-$(. ${BUNDLE_MANIFEST}; echo ${WANTED_ROOT_DEV})}

    BUNDLE_SPC=""
    for BUNDLE in ${DEPLOY_DIR_IMAGE}/*-${WANTED_ROOT_DEV}-${MACHINE}-${BUNDLE_VERSION}-*.sfsuc
    do
        BUNDLE=$(echo ${BUNDLE} | sed -e "s,${DEPLOY_DIR_IMAGE_BASE}/,,")
        NAME=$(echo ${BUNDLE} | sed -e "s,updatable-,," -e "s,-bundle-.*\.sfsuc,," -e 's,-,+,g')
	MANI="${MANI}${MANISPC}\"${NAME}\": \"${BUNDLE}\""
	MANISPC=",
	"
	BUNDLE_LIST="${BUNDLE_LIST}${BUNDLE_SPC}${BUNDLE}"
	BUNDLE_SPC=" "
    done
done

APPLY_TIMESTAMP_ISO="$APPLY_TIMESTAMP"
test "x$APPLY_TIMESTAMP" = "xnull" || APPLY_TIMESTAMP_ISO="\"$(date -d "${APPLY_TIMESTAMP}" --iso-8601=seconds | sed -e 's/+.*//g')\""

MANIFEST="{
    \"${BUNDLE_VERSION}\": {
        ${MANI},
        \"apply\": ${APPLY_TIMESTAMP_ISO}
    }
}"

REPOS=$(oe_builddir repos)
for d in ${REPOS}
do
    test -d ${d}/scripts/deploybundles.d || continue
    for dbd in ${d}/scripts/deploybundles.d/*
    do
	source $dbd
    done
done
