#!/bin/sh

set -x
set -e

DEFAULT_IMAGES_curie="rdm-hp2-image rdm-hp2-xbmc-image"
DEFAULT_IMAGES_bohr="rdm-hp2-image"

MKIMGS="`echo $0 | sed -e 's/mkdeployimgs/mkimgs/'`"
MACHINES="${MACHINES:-curie bohr}"
for MACHINE in ${MACHINES}
do
    DEFAULT_IMAGES_NM=`eval echo DEFAULT_IMAGES_${MACHINE}`
    images=${IMAGES:-$(eval echo \$$DEFAULT_IMAGES_NM)}
    if [ "$1" = "--dev" ]
    then
        IMG_LIST="${images}"
	for IMG in $images
	do
	    test $(echo ${IMG} | fgrep '-dev-') && continue
	    DEV_IMG="`echo $IMG | sed -e 's/-image/-dev-image/'`"
	    IMG_LIST="${IMG_LIST} $DEV_IMG"
	done
	images="$IMG_LIST"
    fi

    env MACHINE=$MACHINE "${MKIMGS}" ${images}
    DEPLOY_DIR_IMAGE="tmp/deploy/images/${MACHINE}"
    SYSIMG_VERSION=$(. ${DEPLOY_DIR_IMAGE}/.settings; echo ${SYSIMG_VER})
    (cd `dirname $0`/post-flash && tar cjf - .) >${DEPLOY_DIR_IMAGE}/post-flash-${SYSIMG_VERSION}.tar.bz2
    (cd ${DEPLOY_DIR_IMAGE} && ln -sf post-flash-${SYSIMG_VERSION}.tar.bz2 post-flash.tar.bz2)
done
